FROM ruby:2.6-alpine

RUN apk add --no-cache --update build-base \
                                linux-headers \
                                git \
                                mysql-dev \
                                nodejs \
                                tzdata \
                                ruby-dev

WORKDIR /app
ADD Gemfile /app
ADD Gemfile.lock /app
RUN gem install bundler
RUN bundle install --without development production
RUN rake db:create db:migrate

COPY . /app
RUN rake db:create db:migrate

EXPOSE 3000

CMD rspec