---
version: "3.7"
services:
  runner:
    build:
      context: ./
      dockerfile: Dockerfile.test
    command: rspec
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://root:aiPhu1duCa2o@db/freebail-wedding-api_test
      RACK_ENV: test
  db:
    environment:
      MYSQL_ROOT_PASSWORD: aiPhu1duCa2o
    image: mysql:5.7