---
version: "3.7"
services:
  runner:
    build:
      context: ./
      dockerfile: Dockerfile.test
    command: rspec
    depends_on:
      - db
    entrypoint: ["/app/bin/wait_for", "db:3306", "--"]
    environment:
      DATABASE_URL: mysql2://root:aiPhu1duCa2o@db/freebail-wedding-api_test
      RACK_ENV: test
    volumes:
      - ./:/app/:rw
  db:
    environment:
      MYSQL_ROOT_PASSWORD: aiPhu1duCa2o
    image: mysql:5.7
