apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: freebail-wedding-api
  name: freebail-wedding-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: freebail-wedding-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: freebail-wedding-api
    spec:
      containers:
      - image: gcr.io/GOOGLE_CLOUD_PROJECT/freebail-wedding-api:COMMIT_SHA
        name: freebail-wedding-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
